#!/bin/bash

######################################################################
# FUNCTIONS
######################################################################
printHelp () {
    echo ""
    echo "Temporarily grant ssh access to friends."
    echo ""
    echo "Usage:"
    echo "    $0 [options] <friendUSER_NAME>"
    echo ""
    echo "[options]"
    echo "    -h : Print this help"
    echo "    -g : Github identity provider"
    echo "    -i : Show IP address"
    echo ""
    echo "<friendUSER_NAME>"
    echo "    The friend USER_NAME which will be granted access"
    echo ""
}

######################################################################
identityDownloadKeyGithub () {

    USER_KEY=`curl -s https://github.com/$USER_NAME.keys`

    if [[ -z $USER_KEY ]]; then
        echo "User $USER_NAME has no keys on Github."
        exit 5
    fi

    if [[ "$USER_KEY" == "Not Found" ]]; then
        echo "User $USER_NAME not found on Github."
        exit 5
    fi
    echo $USER_KEY
}

######################################################################
stopCallback () {
    if grep -v "$USER_KEY" $HOME/.ssh/authorized_keys > $HOME/.ssh/tmp; then
        cat $HOME/.ssh/tmp > $HOME/.ssh/authorized_keys && rm $HOME/.ssh/tmp;
    else
        rm $HOME/.ssh/authorized_keys && rm $HOME/.ssh/tmp;
    fi
}

######################################################################
getIP() {
    echo $(curl -s checkip.dyndns.org | sed -e 's/.*Current IP Address: //' -e 's/<.*$//')
}

######################################################################
# VARS
######################################################################
IDENTITY_GITHUB=0
IDENTITY_SERVICE_NAME=""
USER_NAME=""
USER_KEY=""
SHOW_IP_ADDRESS=0
LOCAL_IP_ADDRESS="THIS_MACHINE_IP"
TEXT_BOLD=$(tput bold)
TEXT_NORMAL=$(tput sgr0)

######################################################################
# TEST DEPS
######################################################################
curl --help > /dev/null
if [[ $? -ne 0 ]]; then
    echo "$0: \`curl --help\` failed in this environment."
    exit 1
fi

SSH_KEYGEN_CMD=$(which ssh-keygen 2> /dev/null)
if [[ $? -ne 0 ]]; then
    echo "$0: ssh-keygen command not available."
    exit 1
fi

######################################################################
# PARSE ARGUMENTS
######################################################################
while getopts "hgi" o; do
    case "${o}" in
        h)
            printHelp
            exit 0
            ;;
        g)
            IDENTITY_GITHUB=1
            shift
            ;;
        i)
            SHOW_IP_ADDRESS=1
            shift
            ;;
        *)
            printHelp
            exit 0
            ;;
    esac
done
USER_NAME=$1

######################################################################
# TEST ARGUMENTS
######################################################################
if [ -z "$USER_NAME" ]; then
    echo "$0: No friend USER_NAME provided"
    printHelp
    exit 4
fi


if [[ $IDENTITY_GITHUB -eq 1 ]]; then
    IDENTITY_SERVICE_NAME="github"
    USER_KEY=$(identityDownloadKeyGithub)
else
    echo "$0: No identity provider provided"
    printHelp
    exit 5
fi

######################################################################
TMP_KEY_FILE=/tmp/.sshForFriends.$USER_NAME-$USER-$IDENTITY_SERVICE_NAME.keys
echo $TMP_KEY_FILE
echo $USER_KEY > $TMP_KEY_FILE
ssh-keygen -l -f $TMP_KEY_FILE > /dev/null
if [[ $? -ne 0 ]]; then
    echo "$0: Downloaded key is invalid"
    exit 6
fi
rm -f $TMP_KEY_FILE


######################################################################
if [[ SHOW_IP_ADDRESS -eq 1 ]]; then
    LOCAL_IP_ADDRESS=$(getIP)
fi

######################################################################
echo "Acquired key for user ${TEXT_BOLD}$USER_NAME${TEXT_NORMAL} from ${TEXT_BOLD}$IDENTITY_SERVICE_NAME${TEXT_NORMAL}."
echo "Your friend ${TEXT_BOLD}$USER_NAME${TEXT_NORMAL} is now able to login via ssh using : ${TEXT_BOLD}ssh $USER@$LOCAL_IP_ADDRESS${TEXT_NORMAL}"
echo ""
echo "Login authorization will stop after this program terminates."
echo "Press ^C to exit."

######################################################################
trap "stopCallback; exit 0" SIGHUP SIGINT SIGTERM
mkdir -p $HOME/.ssh/
echo "$USER_KEY" >> $HOME/.ssh/authorized_keys
sleep infinity &
wait